/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import graph.GrafoCasa;
import graph.Grupo;
import graph.Pilha2;
import javax.swing.JFrame;
import search.UFS;


/**
 *
 * @author meimarcel
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    private Music musica;
    public final int seq = 12;
    public GrafoCasa caminho;
    public UFS ufs;
    public Grupo atual;
    public Pilha2 pilha = new Pilha2();
     public Grupo[] rotaCasa = new Grupo[12];
    
    public TelaInicial() {
        setVisible(true);
        setTitle("Cavaleiros Do Zodiaco");
        setSize(1000,840);
        setLocationRelativeTo(null);
        setResizable(false);
        caminho = new GrafoCasa();
        musica = new Music("src//sounds//Opening.wav");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
        initComponents();
        ufs = new UFS(caminho);
        ufs.buscar();
        musica.loop();
        double total = 0;
        atual = (Grupo) caminho.vertices.get(caminho.vertices.size() - 1);
        while(atual != null) {            
            total += atual.peso;
            pilha.push(atual);
            atual = atual.pai;
        }
        System.out.println(total);
        System.out.println();
        int cont = pilha.cont;
        for(int i = 0; i < cont; i++){
            rotaCasa[i] = pilha.pop();
            System.out.println("nivel:"+rotaCasa[i].nivel);
            System.out.println("peso:"+rotaCasa[i].peso);
            for(int k = 0 ; k < 5; k++) {
                System.out.println("vida"+k+":"+rotaCasa[i].p[k]);
            }
            System.out.println();

        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(getLocation());
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 840));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Play.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setOpaque(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PlaySelect.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 490, 210, 60);
        jButton1.setBackground(new java.awt.Color(204, 204, 255,0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 590, 310, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicialBG.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        musica.stop();
        this.dispose();
        TelaLabirinto tela = new TelaLabirinto();
        tela.rotaCasa = this.rotaCasa;
        tela.ativar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
